name: 15min更新一次

on:
  workflow_dispatch:
  schedule:
  - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Set timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d %H:%M')"
  
      - name: Git config and checkout
        run: |
          git config --global user.email "ouweijie123@outlook.com"
          git config --global user.name "update actioner"
          git checkout gh_pages
          git pull

      - name: run update_data.sh
        run: |
          pip install -r ./requirements.txt
          bash ./update_data.sh

      - name: run update_display.sh
        run: |
          bash ./update_display.sh

      - name: Check for changes
        id: git-status
        run: |
          git diff --quiet || echo "::set-output name=changes::true"

      - name: Git add and commit
        run: |
          if [[ "${{ steps.git-status.outputs.changes }}" == "true" ]]; then
            git add .
            git commit -m "update_data_15minly_${{ steps.timestamp.outputs.timestamp }}"
          else
            echo "No changes detected. Skipping commit."

      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          branch: gh_pages