name: 每天更新一次

on:
    workflow_dispatch:
    schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d %H:%M')"

      - name: Git config and checkout
        run: |
          git config --global user.email "ouweijie123@outlook.com"
          git config --global user.name "update actioner"
          git checkout gh_pages

      - name: run update_data_daily.sh
        run: |
          pip install -r ./requirements.txt
          bash ./update_data_daily.sh
  
      - name: Git add and commit
        run: |
          git pull
          git add .
          git commit -m "update_data_daily_${{ steps.timestamp.outputs.timestamp }}"

      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          branch: gh_pages